### ISSUE TITLE
Rename project and modules and update all dependencies

### ISSUE THREAD

**Issue by martinschimak** [camunda-community-hub/camunda-platform-scenario#57]
Main POM
```
<groupId>org.camunda.bpm.extension.scenario</groupId>
<artifactId>camunda-platform-scenario-runner</artifactId>
```

Root POM (with a 'project' group id used for all not published artifacts, too, like integration test modules)
```
<groupId>org.camunda.bpm.extension.scenario.project</groupId>
<artifactId>camunda-platform-scenario-root</artifactId>
```

Deprecated POM (used so far)
```
<groupId>org.camunda.bpm.extension</groupId>
<artifactId>camunda-bpm-assert-scenario</artifactId>
```

**Comment by martinschimak** [comment]
@celanthe Could you have a look at the description here, too? Does the main POM and project root POM ids make sense to you, in particular considering other Camunda Community projects? Furthermore, I wonder whether I should stick to the org.camunda.**bpm**.* prefix convention ... will the core product keep these group ids for the foreseeable future? Will it keep the package names (I assume so)? I'm asking, because before releasing 2.0.0 of this community extension I would have to chance to bring such things to the most current state. :-) Thank you for helping me!

**Comment by celanthe** [comment]
Hi @martinschimak! This description/main POM and project root POM look good to me. I synced with @ThorbenLindhauer regarding the prefix convention, and this was what he had to say there: 

"We have no plans to change Java package names or Maven group ids in the core product in the future. Our only request for extension maintainers is that they use distinct package and group names that won't lead to confusion with the core product (e.g. it would be bad if they use the same packages that we have in the core engine)."

I hope this information helps! Please let me know if there's anything else I can assist with. I am happy to help.

**Comment by martinschimak** [comment]
Super cool - thank you 🙏  - really helpful.
