### ISSUE TITLE
Please release 1.1.1 hotfix release - thank you

### ISSUE THREAD

**Issue by martinschimak** [camunda-community-hub/camunda-platform-scenario#61]
Dear @celanthe - stupid things happen - I had to directly publish a small hotfix release - can you please publish 1.1.1, too ... thank you!

**Comment by celanthe** [comment]
Hi @martinschimak! I've gone ahead and released this hotfix to Maven Central! It should hopefully be available soon! :)

**Comment by martinschimak** [comment]
Thank you so much @celanthe. It works and is already visible on Maven Central.
