### ISSUE TITLE
Enable Travis CI (.com) for Camunda Platform Scenario

### ISSUE THREAD

**Issue by martinschimak** [camunda-community-hub/camunda-platform-scenario#62]
Hi @celanthe I had travis-ci.org running for this library. Now after the migration to camunda-community-hub it is not working anymore. Furthermore, travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. I therefore requested authorization for this repository via travis-ci.com - can you grant and enable this for me? 

That'd be awesome! 😄 
Thank you, Martin

**Comment by celanthe** [comment]
Hi @martinschimak! Thanks for opening this issue! I've approved the authorization and enabled Travis-CI.com on this repository! Do I need to do anything else, or is that all set? :)

**Comment by martinschimak** [comment]
All set! Awesome, thank you!
