### ISSUE TITLE
refactore multi-module project structure

### ISSUE THREAD

**Issue by jangalinski** [camunda-community-hub/camunda-platform-scenario#7]
Hi Martin

using the org.camunda.bpm.extension groupId leads to a very unstructured maven repo view, where all extensions, there parents/roots and their examples lie in the same folder. Not only is this "ugly", it also gets annoying when you are using autocompletion when you are writing your pom ... you just get a lot of valid suggestions although you are only interested in one extension.

For the soon to come spring-boot extension 2.0, I refactored the structucture to look like this: https://app.camunda.com/nexus/content/repositories/camunda-bpm-community-extensions-snapshots/org/camunda/bpm/extension/springboot/
- the extension has its own groupid
- on the toplevel are only the extensions you really would want to use
- examples are a sub folder
- everything related to project structure (the root poms and the documentation so far) are in the project folder.

I want to discuss this layout as a new blueprint for new extensions since it (imho) makes navigation a lot simpler without interfering with the poms too much. What do you think? 
If you like it, I could assist refactoring the assert-scenario structure ...
Also: we had the discussion "how do we name "pure-parent" poms that are only required to group modules ... and we agreed to use "_-root". I noticed that you used "_-parent" again. Though even "*-foo" would be okay, for the sake of unification, would you mind changing it?

**Comment by martinschimak** [comment]
Hi @jangalinski I will restructure and rename group ids and artifact ids of this project rather soon. Maybe you can help me here with another updated comment about what of your original comment is still relevant, what are the current conventions you use etc. That'd be awesome, thank you. Martin

**Comment by martinschimak** [comment]
Closed with #65
