### ISSUE TITLE
Please push 2.0.0.alpha.1 to maven central

### ISSUE THREAD

**Issue by martinschimak** [camunda-community-hub/camunda-platform-scenario#80]
Hey @celanthe I staged a first 2.0 version 2.0.0.alpha.1 - now including not just one, but three jar artifacts: **camunda-platform-scenario-runner**, **camunda-platform-scenario-cucumber** and **camunda-platform-scenario-report** - could you please publish to maven central! Thank you! ❤️ 🙏

**Comment by celanthe** [comment]
Hi @martinschimak! This has been completed, and should be available soon on Maven Central! :)
